services:
  mysql:
    image: mysql:8.0
    container_name: file_sharing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: file_sharing
      MYSQL_USER: default 
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: for initialization scripts
